# Generated by Django 2.2.5 on 2021-07-15 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20210715_1620'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rule',
            new_name='HouseRule',
        ),
    ]
